# How to initialise MAAS for production
# https://maas.io/docs/how-to-do-a-fresh-install-of-maas#heading--init-maas-production-3-3

- name: Create a suitable PostgreSQL user
  ansible.builtin.shell: -i -u postgres psql -c "CREATE USER \"{{MAAS_DBUSER}}\" WITH ENCRYPTED PASSWORD '{{MAAS_DBPASS}}'"
  # ansible.builtin.shell: -i -u postgres psql -c "CREATE USER \"{{MAAS_DBUSER}}\" WITH ENCRYPTED PASSWORD '{{MAAS_DBPASS}}'"
  args:
    # chdir: somedir/
    creates: somelog.txt
  become: true


- name: init test deployment
  ansible.builtin.shell: maas init region+rack --database-uri maas-test-db:///
  args:
    # chdir: somedir/
    creates: somelog.txt
  become: true
