# https://maas.io/docs/how-to-do-a-fresh-install-of-maas

- name: Install MAAS
  community.general.snap:
    name: maas
    channel: "{{channel}}"
  become: true

- name: Disable and stop systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: false
  become: true

- name: Install PostgreSQL
  ansible.builtin.apt:
    pkg:
    - postgresql
  become: true