# Todo use Debconf
- name: init test deployment
  ansible.builtin.shell: maas init region+rack --database-uri maas-test-db:///
  become: true


- name: maas createadmin
  ansible.builtin.shell: "maas createadmin --username {{MAAS_DBUSER}} --password {{MAAS_DBPASS}} --email {{email}}"
  become: true